"""daily goals, synonyms, known words

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 04:58:10.823168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_words", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("known", sa.Boolean(), server_default="false", nullable=False)
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("daily_article_goal", sa.Integer(), server_default="5", nullable=False)
        )
        batch_op.add_column(
            sa.Column("daily_word_goal", sa.Integer(), server_default="5", nullable=False)
        )

    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.add_column(sa.Column("synonyms", sa.JSON(), server_default="[]", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_column("synonyms")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("daily_word_goal")
        batch_op.drop_column("daily_article_goal")

    with op.batch_alter_table("user_words", schema=None) as batch_op:
        batch_op.drop_column("known")

    # ### end Alembic commands ###
